Added AzEl coordinate system.
jacob-pro/cspice-rs pull request #1
Opened 2022-09-02 19:11 UTC by cmleinz

Hi Jacob,

I'm looking to add support for the AzEl coordinate system. Unfortunately we can't implement `From` due to [azlrec_c](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/azlrec_c.html) requiring two additional parameters. I'm wondering if you have a better idea as to how to approach this implementation. 

Also there seems to be some issues with my tests preventing me from constraining epsilon further. I'm not sure if this exists in cspice or not.

Thanks for your work on this project!

2022-09-02 19:34 UTC, jacob-pro commented
Hi @cmleinz

Thank you very much for this PR, I will be taking a proper look at it when I'm free next week!

Yeah the high level crate is still very much in the experimental stage, trying to figure out an ergonomic API, and not fully tested yet - hence why I haven't published it yet.

2022-09-05 14:58 UTC, jacob-pro commented
Build looks like it is failing for reasons unrelated to your change: 
https://github.com/jacob-pro/cspice-rs/runs/8162854702?check_suite_focus=true
The failing clippy lint was only added recently in Rust 1.63.0 which would explain why
https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq

It should be very easy to resolve though if you are happy to?

2022-09-06 06:34 UTC, cmleinz commented
Yep no problem I'll take a look at the new clippy warnings a little later this week.

2022-09-10 17:31 UTC, jacob-pro requested changes
Also sorry I forgot to submit this one as well!

2022-09-10 17:31 UTC, jacob-pro commented on cspice/src/coordinates.rs
> +        rect
This looks like a duplicate of `Rectangular::from_azel` ? Ideally we should only have one implementation, if you want to have helper methods that call the other one that is fine, although probably not needed.

The `from_azel` should be the primary implementation so as to match the rust convention of implementing `From` rather than `To` - similar to what I have done for the `DateTime::from_et`

2022-09-11 13:10 UTC, jacob-pro approved these changes

2022-09-11 13:10 UTC, merged

2022-09-11 13:11 UTC, jacob-pro commented
thanks again @cmleinz !